name: Update Contributors

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Contributors
        run: |
          CONTRIBUTORS=$(curl -s https://api.github.com/repos/zakarialabib/mystockmaster/contributors | jq -r '.[].login')
          sed -i '/## Contributors/q' README.md
          echo -e "## Contributors\n\n$(printf -- '-   [%s](https://github.com/%s)\n' $CONTRIBUTORS)" >> README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update Contributors [skip ci]"
          git push
